baseURL = 'https://wynn.moe/'
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-cn'
title = 'Wynn'
theme = 'rio'
enableRobotsTXT = true
hasCJKLanguage = true
[params]
  description = 'Wynn 的个人主页。'
  email = 'wynnzeng2010@gmail.com'
  homePosts = 3
  homeFriends = 4
[taxonomies]
  tag = 'tags'
  category = 'categories'
[permalinks]
  blog = '/blog/:contentbasename/'
[markup.goldmark.renderer]
  unsafe = true
[params.comments]
  enabled = true
  repo = 'crepusveniet/wynn.moe'
  repoId = 'R_kgDOUc53Ww'
  category = 'Announcements'
  categoryId = 'DIC_kwDOUc53W84DFtUb'
  mapping = 'pathname'
  strict = 0
  reactionsEnabled = 0
  emitMetadata = 0
  inputPosition = 'top'
  theme = 'https://wynn.moe/css/giscus.css?v=3'
  lang = 'en'
  loading = 'lazy'
[params.article]
  license = 'CC BY-NC-SA 4.0'
[markup.highlight]
  noClasses = true
  style = 'friendly'
